### ISSUE TITLE
java.lang.IllegalStateException: Cannot load configuration class: scorekeep.WebConfig

### ISSUE THREAD

**Issue by sharuzzaman** [awslabs/eb-java-scorekeep#6]
Hi,

I tried downloading the source from https://github.com/awslabs/eb-java-scorekeep/releases/download/v1.3/eb-java-scorekeep-v1.zip and then deploy it to Elastic Beanstalk.

After deploying, the application is not working, and in /var/log/web-1.log , I got this message:

2017-08-15 08:34:36.665  INFO 2341 --- [           main] scorekeep.Application                    : Starting Application on ip-172-31-6-148 with PID 2341 (/v
ar/app/current/build/libs/scorekeep-api-1.0.0.jar started by webapp in /var/app/current)
2017-08-15 08:34:36.698  INFO 2341 --- [           main] scorekeep.Application                    : No active profile set, falling back to default profiles:
default
2017-08-15 08:34:37.044  INFO 2341 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.Anno
tationConfigEmbeddedWebApplicationContext@5b37e0d2: startup date [Tue Aug 15 08:34:37 UTC 2017]; root of context hierarchy
2017-08-15 08:34:45.078 ERROR 2341 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Cannot load configuration class: scorekeep.WebConfig
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:416) ~[spr
ing-context-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:263) ~[spring-c
ontext-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:284)
~[spring-context-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:130)
~[spring-context-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]

Then supervisord keep restarting the application, but it will died after that.

I have rebuild the Elastic Beanstalk environment, but the issue still happen.

Configuration: 
64bit Amazon Linux 2017.03 v2.5.3 running Java 8

**Comment by sharuzzaman** [comment]
Tried to deploy master branch by downloading the zip from "clone or download" button, but still got the same issue

**Comment by mwunderl** [comment]
Hi sharuzzaman,

Looks like that release has an extra folder at the top level of the archive which will cause problems with Elastic Beanstalk. I'll cut a new release to fix.

Thanks,
-Michael

**Comment by mwunderl** [comment]
I've posted a new release. There was a separate issue that caused an exception when an email address for  notifications was not configured.
https://github.com/awslabs/eb-java-scorekeep/releases/tag/v1.5

**Comment by sharuzzaman** [comment]
Will test the new release soon
