### ISSUE TITLE
Aspect for X-Ray

### ISSUE THREAD

**Issue by paolocarrasco** [awslabs/eb-java-scorekeep#7]
Hi guys,
Are there plans to create an example for this using Spring AOP for cross-cutting concerns like X-Ray?
Currently we are trying to avoid many responsibilities in the code that don't belong to the class, and for that we are using AOP.
This is an example of what we are doing, but it is not working in the case of errors.
```
@Aspect
public class XRayAspect {

    private Logger logger = LoggerFactory.getLogger(XRayAspect.class);

    @Pointcut("@annotation(com.netflix.hystrix.contrib.javanica.annotation.HystrixCommand) && execution(* *(..))")
    public void annotationHystrixPointCut() {

    }

    @Before("annotationHystrixPointCut()")
    public void createSubsegment(JoinPoint joinPoint) {
        logger.info("---------------------- it executed before " + joinPoint);
        AWSXRay.getThreadLocal().addSubsegment(AWSXRay.beginSubsegment(joinPoint.getSignature().getName()));

    }

    @AfterThrowing(pointcut = "annotationHystrixPointCut()", throwing = "ex")
    public void addExceptiontoSubSegment(Exception ex) {
        logger.error("---------------------- it happened an error ", ex);
        AWSXRay.getCurrentSubsegment().addException(ex);
    }

    @After("annotationHystrixPointCut()")
    public void finalizeSubsegment() {

        logger.info("---------------------- it happened after ");
        AWSXRay.endSubsegment();
    }
}
```
I would appreciate any feedback you could provide.

**Comment by mwunderl** [comment]
Hi Paolo,
Thanks for your feedback. Do you see anything in the [SDK log](http://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-configuration.html#xray-sdk-java-configuration-logging) when you try to record an exception with this code?
-Michael

**Comment by paolocarrasco** [comment]
Yes, this is one of the errors we get:
```
2017-09-04 11:35:23,269 ERROR [autenticacion-Executor-1] ExceptionHandlingAsyncTaskExecutor: Caught async exception
com.amazonaws.xray.exceptions.SegmentNotFoundException: Thread has no segment in progress.
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at com.amazonaws.xray.strategy.RuntimeErrorContextMissingStrategy.contextMissing(RuntimeErrorContextMissingStrategy.java:17)
at com.amazonaws.xray.AWSXRayRecorder.getCurrentSubsegment(AWSXRayRecorder.java:477)
at com.amazonaws.xray.AWSXRay.getCurrentSubsegment(AWSXRay.java:116)
at pe.com.foobar.mobileservices.appmovil.config.XRayAspect.afterThrowing(XRayAspect.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:611)
at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:66)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
at pe.com.foobar.mobileservices.appmovil.repository.impl.PortalAppsRepositoryImpl$$EnhancerBySpringCGLIB$$f13c6b6d.insertActionCode(<generated>)
at pe.com.foobar.mobileservices.appmovil.dao.impl.ActionCodeDaoImpl.executeInsertActionCode(ActionCodeDaoImpl.java:52)
at pe.com.foobar.mobileservices.appmovil.dao.impl.ActionCodeDaoImpl.lambda$insertActionCode$1(ActionCodeDaoImpl.java:40)
at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:63)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```
On errors we are using RuntimeExceptions, which create different threads, and I think the segment is being bound to the main thread... (thinking aloud).

**Comment by mwunderl** [comment]
When you create a new thread, you need to pass the open segment or subsegment to the new thread manually. Use [GetTraceEntity](http://docs.aws.amazon.com/xray-sdk-for-java/latest/javadoc/com/amazonaws/xray/AWSXRayRecorder.html#getTraceEntity--) to get the segment or subsegment Entity, pass it to the new thread, and then hand it back to the SDK with [SetTraceEntity](http://docs.aws.amazon.com/xray-sdk-for-java/latest/javadoc/com/amazonaws/xray/AWSXRayRecorder.html#setTraceEntity-com.amazonaws.xray.entities.Entity-).

**Comment by paolocarrasco** [comment]
Hi @mwunderl, thanks!
I finally found that the best approach to register the exceptions is by using an `around` aspect; `before` and `after` are useful only on annotations and metadata.

**Comment by mwunderl** [comment]
I've added some information about multithreading to the developer guide-
[Using Instrumented Clients in Worker Threads](https://docs.aws.amazon.com/xray/latest/devguide/scorekeep-workerthreads.html)
[Passing Segment Context between Threads in a Multithreaded Application ](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-multithreading.html)
